[package]
name = "nodash"
type = "lib"
authors = ["Oleh Misarosh <olehmisar@gmail.com>"]

[dependencies]
sha256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/sha256" }
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
